apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: evaluation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
        - name: evaluation-service
          image: 434473100946.dkr.ecr.us-east-1.amazonaws.com/evaluation-service:v1.0.2
          ports:
            - containerPort: 8004
              name: http
          env:
            - name: SERVICE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: evaluation-service-secrets
                  key: SERVICE_API_KEY
            
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: PORT

            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: REDIS_URL
            
            - name: FLAG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: FLAG_SERVICE_URL

            - name: TARGETING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: TARGETING_SERVICE_URL

            - name: AWS_SQS_URL
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: AWS_SQS_URL

            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: AWS_REGION

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: evaluation-service-config
                  key: AWS_SECRET_ACCESS_KEY

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
