apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secrets
  namespace: evaluation-service
type: Opaque
stringData:
  SERVICE_API_KEY: "tm_key_95dd3e6c2d773d1ef6f70c776b04fb4b8531526bf1424a259047f83e57dc0fa8"